# on: 
#   push:
#     tags:
#     - '*'

# name: "Telegram Post"

# jobs:
#   notifyTelegram:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Telegram<apk>
#       uses: appleboy/telegram-action@master
#       with:
#         to: ${{ secrets.TELEGRAM_TO }}
#         token: ${{ secrets.TELEGRAM_TOKEN }}
#         document: build/app/outputs/flutter-apk/*.apk

# name: "Check"
# on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: "npm ci"
      if: endsWith(github.ref, '-release')
      run: npm ci

    - name: "npm install"
      if: endsWith(github.ref, '-release') == false
      run: npm install

    - name: "npm run build"
      run: npm run build

    - name: "npm run test"
      run: npm run test

    - name: "check for uncommitted changes"
      # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
      if: endsWith(github.ref, '-release')
      run: |
        git diff --exit-code --stat -- . ':!node_modules' \
        || (echo "##[error] found changed files after build. please 'npm run build && npm run format'" \
                 "and check in all changes" \
            && exit 1)
    - name: notification
      if: cancelled() == false
      uses: ./
      with:
        botToken: ${{ secrets.TELEGRAM_TOKEN }}
        chatId: ${{ secrets.TELEGRAM_TO }}
        jobStatus: ${{ job.status }}
        skipSuccess: false
