# on: 
#   push:
#     tags:
#     - '*'

# name: "Telegram Post"

# jobs:
#   notifyTelegram:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Telegram<apk>
#       uses: appleboy/telegram-action@master
#       with:
#         to: ${{ secrets.TELEGRAM_TO }}
#         token: ${{ secrets.TELEGRAM_TOKEN }}
#         document: build/app/outputs/flutter-apk/*.apk

# name: Releases

# on: 
#   push:
#     tags:
#     - '*'

# jobs:

#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#     - uses: actions/checkout@v2
#     - uses: ncipollo/release-action@v1
#       with:
#         artifacts: "release.tar.gz,foo/*.txt"
#         bodyFile: "body.md"
#         token: ${{ secrets.GITHUB_TOKEN }}